name: checkup_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  date_field: ^3.0.5
  dynamic_color: ^1.6.6
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  localstorage: ^4.0.1+4
  path: ^1.8.3
  provider: ^6.1.1
  share_plus: ^7.0.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
