name: flutter-web-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Prepare flutter
        uses: subosito/flutter-action@v2.12.0

      - name: Analyze code
        run: flutter analyze

      - name: Build for web
        run: flutter build web --base-href "/ziphycheck/"

      - name: Upload build results
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: 'build/web/.'

      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v3.0.1
